### ISSUE TITLE
react-refresh.js?ts=1646804988423:30 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by laclance** [MlkMahmud/binance-dca-bot#23]
```
react-refresh.js?ts=1646804988423:30 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

Hi, all I did was set env variables and run npm i && npm run dev and opened localhost:3000 in browser.
Using Ubuntu 20.04.4 LTS and node 16.9.1

**Comment by MlkMahmud** [comment]
Hi,

Please try running it in an Incognito tab and let me know the results.

**Comment by laclance** [comment]
same error

**Comment by MlkMahmud** [comment]
@laclance Okay. In the app.ts file, comment out this line ```app.use(helmet());```

**Comment by laclance** [comment]
Ah should have known that was the issue, thanks. Obviously better option is to specify content security policy directives.

**Comment by MlkMahmud** [comment]
@laclance I've updated the code to only use helmet in a production environment,  you can pull the latest changes

**Comment by laclance** [comment]
thank you
